"""Model exporter — export models to various formats."""

from __future__ import annotations
from pathlib import Path
from typing import Any


class ModelExporter:
    def __init__(self, display: Any = None):
        self.display = display

    def export(self, model_name: str, fmt: str, output_dir: str) -> bool:
        output = Path(output_dir)
        output.mkdir(parents=True, exist_ok=True)

        if self.display:
            self.display.print_step(f"Exporting {model_name} as {fmt.upper()}...")

        if fmt == "gguf":
            return self._export_gguf(model_name, output)
        elif fmt == "onnx":
            return self._export_onnx(model_name, output)
        elif fmt == "docker":
            return self._export_docker(model_name, output)
        return False

    def _export_gguf(self, model_name: str, output: Path) -> bool:
        script = f'''#!/usr/bin/env python3
"""GGUF export script — requires llama.cpp to be installed."""

import subprocess
import sys

MODEL = "{model_name}"
OUTPUT = "{output}"

# Clone llama.cpp if not present
llama_cpp = OUTPUT / "llama.cpp"
if not llama_cpp.exists():
    subprocess.run(["git", "clone", "https://github.com/ggerganov/llama.cpp", str(llama_cpp)])

# Convert to GGUF
convert = llama_cpp / "convert_hf_to_gguf.py"
if convert.exists():
    subprocess.run([sys.executable, str(convert), MODEL, "--outfile", str(OUTPUT / "model.gguf")])
    print(f"Model exported to {{OUTPUT / 'model.gguf'}}")
else:
    print("Could not find convert script. Install llama.cpp manually.")
'''
        with open(output / "export_gguf.py", "w") as f:
            f.write(script)
        if self.display:
            self.display.print_success(f"GGUF export script written to {output}/export_gguf.py")
        return True

    def _export_onnx(self, model_name: str, output: Path) -> bool:
        script = f'''#!/usr/bin/env python3
"""ONNX export script — requires optimum."""

from optimum.onnxruntime import ORTModelForCausalLM

MODEL = "{model_name}"
OUTPUT = "{output}"

model = ORTModelForCausalLM.from_pretrained(MODEL, export=True)
model.save_pretrained(str(OUTPUT))
print(f"Model exported to {{OUTPUT}}")
'''
        with open(output / "export_onnx.py", "w") as f:
            f.write(script)
        if self.display:
            self.display.print_success(f"ONNX export script written to {output}/export_onnx.py")
        return True

    def _export_docker(self, model_name: str, output: Path) -> bool:
        dockerfile = f'''# Generated by NeuralForge
FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir transformers torch fastapi uvicorn

COPY serve.py .

EXPOSE 8000
CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8000"]
'''
        serve = f'''"""Auto-generated model server."""

from fastapi import FastAPI
from pydantic import BaseModel
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

MODEL = "{model_name}"

app = FastAPI()
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForCausalLM.from_pretrained(MODEL, torch_dtype=torch.float16, device_map="auto")

class GenerateRequest(BaseModel):
    prompt: str
    max_tokens: int = 256
    temperature: float = 0.7

@app.post("/generate")
def generate(req: GenerateRequest):
    inputs = tokenizer(req.prompt, return_tensors="pt", truncation=True, max_length=512)
    with torch.no_grad():
        outputs = model.generate(
            **inputs, max_new_tokens=req.max_tokens, temperature=req.temperature
        )
    text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return {{"response": text}}

@app.get("/health")
def health():
    return {{"status": "ok", "model": MODEL}}
'''
        with open(output / "Dockerfile", "w") as f:
            f.write(dockerfile)
        with open(output / "serve.py", "w") as f:
            f.write(serve)

        if self.display:
            self.display.print_success(f"Docker deployment written to {output}/")
            self.display.print_step(f"Build and run: docker build -t {model_name} {output} && docker run -p 8000:8000 {model_name}")
        return True
